package generator

import (
	"fmt"
	"go/ast"
	"go/token"
	"strings"
)

func GenerateBeanRegister(name string, a ast.Decl) ast.FuncDecl {
	fd := ast.FuncDecl{
		Doc: &ast.CommentGroup{
			List: []*ast.Comment{&ast.Comment{
				Text: fmt.Sprintf("%s : Generated by spring. Do Not Edit", name),
			}},
		},
		Recv: &ast.FieldList{},
		Name: &ast.Ident{
			NamePos: 0,
			Name:    fmt.Sprintf("SpringGenerate%s", strings.ToTitle(name)),
			Obj:     &ast.Object{},
		},
		Type: &ast.FuncType{
			Func:    0,
			Params:  &ast.FieldList{},
			Results: &ast.FieldList{},
		},
		Body: &ast.BlockStmt{
			Lbrace: 0,
			List: []ast.Stmt{&ast.AssignStmt{
				Lhs: []ast.Expr{&ast.Ident{
					NamePos: 0,
					Name:    "instance",
					Obj:     &ast.Object{},
				}},
				TokPos: 0,
				Tok:    0,
				Rhs: []ast.Expr{&ast.UnaryExpr{
					OpPos: 0,
					Op:    token.AND,
					X: &ast.CompositeLit{
						Type:       nil,
						Lbrace:     0,
						Elts:       []ast.Expr{},
						Rbrace:     0,
						Incomplete: false,
					},
				}},
			}, &ast.ExprStmt{}},
			Rbrace: 0,
		},
	}

	return fd
}
